version: '2'

networks:
  mongo-network:
    name: mongo-network

services:
  mongodb:
    image: docker.io/bitnami/mongodb:4.4
    networks:
      - mongo-network
    ports:
      - "27017:27017"
    volumes:
      - 'mongodb_data:/bitnami/mongodb'

volumes:
  mongodb_data:
    driver: local
